// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5WQBIxFP8EkzNzcOoReGXu_L7mYk9SW0',
    appId: '1:851461920948:web:33d61fd1bb7eb74ffe9fe1',
    messagingSenderId: '851461920948',
    projectId: 'minimalchat-cca3f',
    authDomain: 'minimalchat-cca3f.firebaseapp.com',
    storageBucket: 'minimalchat-cca3f.firebasestorage.app',
    measurementId: 'G-LN8DJ8J0GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6p-Aei0l204pq64nbAgo2xK0g7tURTGI',
    appId: '1:851461920948:android:87d1cf4f0ff1dd2bfe9fe1',
    messagingSenderId: '851461920948',
    projectId: 'minimalchat-cca3f',
    storageBucket: 'minimalchat-cca3f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5WQBIxFP8EkzNzcOoReGXu_L7mYk9SW0',
    appId: '1:851461920948:web:d1216e7510f43eedfe9fe1',
    messagingSenderId: '851461920948',
    projectId: 'minimalchat-cca3f',
    authDomain: 'minimalchat-cca3f.firebaseapp.com',
    storageBucket: 'minimalchat-cca3f.firebasestorage.app',
    measurementId: 'G-MH4RT5CLB8',
  );
}
